language: node_js

node_js:
  - 0.10.30

cache:
  directories:
    - node_modules  
    
before_script:
  - npm link
  - mkdir -p shippable/codecoverage

after_success:
  - npm run coverage
  - mv coverage/cobertura-coverage.xml shippable/codecoverage/coverage.xml
  - mocha test -R mocha-lcov-reporter  && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js --verbose


deploy:
  provider: npm
  email:  noam1610@gmail.com

  api_key:
    secure: 
  on:
    tags: true
    all_branches: true
    repo: noam1610/workspace
